### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by onetwothreesudo** [Tasin5541/NextJs-Messenger-Clone#16]
Hello! I followed all the steps correctly so far and deployed with Vercel but there are a few errors:
Error 1: When I try to sign in using Google Auth, there's this " Error 400: redirect_uri_mismatch"
Error 2: When I try to sign in using Github Auth, it sorts of refreshes the web app and doesn't lead me to Github to authenticate my account
Error 3: In the console, it displays this error: "Module not found: Can't resolve 'encoding' in '/vercel/path0/node_modules/node-fetch/lib'"
Please help me

**Comment by onetwothreesudo** [comment]
> Have you set the environment variables on vercel? Also, you have to replace the localhost urls with your vercel url for Google and GitHub login.
Yes, I replaced the localhost:3020 with the website link in both github and google.

**Comment by Tasin5541** [comment]
> > Yes, I replaced the localhost link with the website link in both github and google.

What about the environment variables on vercel?

**Comment by Tasin5541** [comment]
Try the following command
`yarn add encoding --dev`

**Comment by Tasin5541** [comment]
As I have not heard back from the author, I am closing this issue.
